# WARNING: Do not deploy this configuration directly to a production environment
#
# The tutorial docker-compose files have not been written for production deployment and will not 
# scale. A proper architecture has been sacrificed to keep the narrative focused on the learning 
# goals, they are just used to deploy everything onto a single Docker machine. All FIWARE components 
# are running at full debug and extra ports have been exposed to allow for direct calls to services. 
# They also contain various obvious security flaws - passwords in plain text, no load balancing,
# no use of HTTPS and so on. 
# 
# This is all to avoid the need of multiple machines, generating certificates, encrypting secrets
# and so on, purely so that a single docker-compose file can be read as an example to build on, 
# not use directly. 
# 
# When deploying to a production environment, please refer to the Helm Repository
# for FIWARE Components in order to scale up to a proper architecture:
# 
# see: https://github.com/FIWARE/helm-charts/
#
version: '3.8'

services:
  orion:
    image: quay.io/fiware/orion-ld:1.6.0-pre-1615
    hostname: orion
    container_name: fiware-orion-ld
    networks:
      - default
    depends_on:
      - mongo-db
    ports:
      - "1026:1026"
    command: -dbhost mongo-db

  mongo-db:
    image: mongo:4.4
    hostname: mongo-db
    container_name: db-mongo
    networks:
      - default
    ports:
      - "27017:27017"

  battery_controller:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ..:/app
    env_file:
      - ../.env
    depends_on:
      - orion
    command: python soh_estimator.py
    networks:
      - default
